module "environment" {
  source = "../../modules/environment-stack"

  environment                            = "production"
  location                               = var.location
  resource_group_name                    = var.resource_group_name
  acr_name                               = var.acr_name
  acr_resource_group_name                = var.acr_resource_group_name
  github_identity_principal_id           = var.github_identity_principal_id
  container_app_environment_name         = var.container_app_environment_name
  frontend_container_app_name            = var.frontend_container_app_name
  backend_container_app_name             = var.backend_container_app_name
  keycloak_container_app_name            = var.keycloak_container_app_name
  key_vault_name                         = var.key_vault_name
  postgres_server_name                   = var.postgres_server_name
  attachment_storage_account_name        = var.attachment_storage_account_name
  document_intelligence_account_name     = var.document_intelligence_account_name
  content_understanding_account_name     = var.content_understanding_account_name
  document_analysis_storage_account_name = var.document_analysis_storage_account_name
  postgres_administrator_login           = var.postgres_administrator_login
  postgres_administrator_password        = var.postgres_administrator_password
  image_tag                              = var.image_tag
  provision_workloads                    = var.provision_workloads
  contract_legacy_user_columns           = var.contract_legacy_user_columns
  document_analysis_enabled              = var.document_analysis_enabled
  document_intelligence_enabled          = var.document_intelligence_enabled
  content_understanding_enabled          = var.content_understanding_enabled
  allowed_email_domain                   = var.allowed_email_domain
  vnet_address_space                     = var.vnet_address_space
  container_apps_subnet_prefixes         = var.container_apps_subnet_prefixes
  postgres_subnet_prefixes               = var.postgres_subnet_prefixes
  private_endpoint_subnet_prefixes       = var.private_endpoint_subnet_prefixes
}
